### ISSUE TITLE
 http: panic serving 127.0.0.1:51133: runtime error: index out of range [1] with length 0 goroutine 26 [running]:

### ISSUE THREAD

**Issue by Nasim1337** [dzflack/duo-device-health#6]
Upon Duo Heath check I'm getting the following error
Firefox
MacOS 11.6.2
```
2022/08/10 14:29:52 Listening for http
2022/08/10 14:30:19 http: panic serving 127.0.0.1:51770: runtime error: index out of range [1] with length 0
goroutine 35 [running]:
net/http.(*conn).serve.func1()
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:1825 +0xbf
panic({0x12d8f40, 0xc00001e360})
	/usr/local/Cellar/go/1.18.3/libexec/src/runtime/panic.go:844 +0x258
main.generateReportHandler({0x1374a70?, 0xc000206000?}, 0xc0000bc000)
	/Users/peter/duo-device-health/main.go:99 +0xdcb
net/http.HandlerFunc.ServeHTTP(0x25a5e38?, {0x1374a70?, 0xc000206000?}, 0x100e045?)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:2084 +0x2f
net/http.(*ServeMux).ServeHTTP(0xc00000c510?, {0x1374a70, 0xc000206000}, 0xc0000bc000)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:2462 +0x149
net/http.serverHandler.ServeHTTP({0xc000112f90?}, {0x1374a70, 0xc000206000}, 0xc0000bc000)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc000132aa0, {0x1374cc8, 0xc000112ea0})
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:3071 +0x4db
2022/08/10 14:30:19 http: panic serving 127.0.0.1:51777: runtime error: index out of range [1] with length 0
goroutine 4 [running]:
net/http.(*conn).serve.func1()
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:1825 +0xbf
panic({0x12d8f40, 0xc00001e3f0})
	/usr/local/Cellar/go/1.18.3/libexec/src/runtime/panic.go:844 +0x258
main.generateReportHandler({0x1374a70?, 0xc0002060e0?}, 0xc00025c000)
	/Users/peter/duo-device-health/main.go:99 +0xdcb
net/http.HandlerFunc.ServeHTTP(0x25a5e38?, {0x1374a70?, 0xc0002060e0?}, 0x100e045?)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:2084 +0x2f
net/http.(*ServeMux).ServeHTTP(0xc00000c710?, {0x1374a70, 0xc0002060e0}, 0xc00025c000)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:2462 +0x149
net/http.serverHandler.ServeHTTP({0xc00007a4b0?}, {0x1374a70, 0xc0002060e0}, 0xc00025c000)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc000230140, {0x1374cc8, 0xc000112ea0})
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:3071 +0x4db
2022/08/10 14:30:19 http: panic serving 127.0.0.1:51778: runtime error: index out of range [1] with length 0
goroutine 6 [running]:
net/http.(*conn).serve.func1()
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:1825 +0xbf
panic({0x12d8f40, 0xc00001e468})
	/usr/local/Cellar/go/1.18.3/libexec/src/runtime/panic.go:844 +0x258
main.generateReportHandler({0x1374a70?, 0xc0002061c0?}, 0xc00025c100)
	/Users/peter/duo-device-health/main.go:99 +0xdcb
net/http.HandlerFunc.ServeHTTP(0x25a5e38?, {0x1374a70?, 0xc0002061c0?}, 0x100e045?)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:2084 +0x2f
net/http.(*ServeMux).ServeHTTP(0xc00000c910?, {0x1374a70, 0xc0002061c0}, 0xc00025c100)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:2462 +0x149
net/http.serverHandler.ServeHTTP({0xc00007a750?}, {0x1374a70, 0xc0002061c0}, 0xc00025c100)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc000230320, {0x1374cc8, 0xc000112ea0})
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:3071 +0x4db
2022/08/10 14:30:19 http: panic serving 127.0.0.1:51779: runtime error: index out of range [1] with length 0
goroutine 8 [running]:
net/http.(*conn).serve.func1()
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:1825 +0xbf
panic({0x12d8f40, 0xc00001e4e0})
	/usr/local/Cellar/go/1.18.3/libexec/src/runtime/panic.go:844 +0x258
main.generateReportHandler({0x1374a70?, 0xc0002062a0?}, 0xc00025c200)
	/Users/peter/duo-device-health/main.go:99 +0xdcb
net/http.HandlerFunc.ServeHTTP(0x25a5e38?, {0x1374a70?, 0xc0002062a0?}, 0x100e045?)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:2084 +0x2f
net/http.(*ServeMux).ServeHTTP(0xc00000cb10?, {0x1374a70, 0xc0002062a0}, 0xc00025c200)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:2462 +0x149
net/http.serverHandler.ServeHTTP({0xc00007a9f0?}, {0x1374a70, 0xc0002062a0}, 0xc00025c200)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc000230500, {0x1374cc8, 0xc000112ea0})
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:3071 +0x4db
2022/08/10 14:30:19 http: panic serving 127.0.0.1:51780: runtime error: index out of range [1] with length 0
goroutine 10 [running]:
net/http.(*conn).serve.func1()
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:1825 +0xbf
panic({0x12d8f40, 0xc00001e558})
	/usr/local/Cellar/go/1.18.3/libexec/src/runtime/panic.go:844 +0x258
main.generateReportHandler({0x1374a70?, 0xc000206380?}, 0xc00025c300)
	/Users/peter/duo-device-health/main.go:99 +0xdcb
net/http.HandlerFunc.ServeHTTP(0x25a5e38?, {0x1374a70?, 0xc000206380?}, 0x100e045?)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:2084 +0x2f
net/http.(*ServeMux).ServeHTTP(0xc00000cd10?, {0x1374a70, 0xc000206380}, 0xc00025c300)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:2462 +0x149
net/http.serverHandler.ServeHTTP({0xc00007ac90?}, {0x1374a70, 0xc000206380}, 0xc00025c300)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc0002306e0, {0x1374cc8, 0xc000112ea0})
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:3071 +0x4db
2022/08/10 14:30:19 http: panic serving 127.0.0.1:51781: runtime error: index out of range [1] with length 0
goroutine 21 [running]:
net/http.(*conn).serve.func1()
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:1825 +0xbf
panic({0x12d8f40, 0xc0000a80a8})
	/usr/local/Cellar/go/1.18.3/libexec/src/runtime/panic.go:844 +0x258
main.generateReportHandler({0x1374a70?, 0xc00009c1c0?}, 0xc0000bc100)
	/Users/peter/duo-device-health/main.go:99 +0xdcb
net/http.HandlerFunc.ServeHTTP(0x25a5e38?, {0x1374a70?, 0xc00009c1c0?}, 0x100e045?)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:2084 +0x2f
net/http.(*ServeMux).ServeHTTP(0xc00008c110?, {0x1374a70, 0xc00009c1c0}, 0xc0000bc100)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:2462 +0x149
net/http.serverHandler.ServeHTTP({0xc00009e120?}, {0x1374a70, 0xc00009c1c0}, 0xc0000bc100)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc0000c0000, {0x1374cc8, 0xc000112ea0})
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:3071 +0x4db
2022/08/10 14:30:19 http: panic serving 127.0.0.1:51782: runtime error: index out of range [1] with length 0
goroutine 37 [running]:
net/http.(*conn).serve.func1()
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:1825 +0xbf
panic({0x12d8f40, 0xc000150138})
	/usr/local/Cellar/go/1.18.3/libexec/src/runtime/panic.go:844 +0x258
main.generateReportHandler({0x1374a70?, 0xc00018a1c0?}, 0xc00019e200)
	/Users/peter/duo-device-health/main.go:99 +0xdcb
net/http.HandlerFunc.ServeHTTP(0x25a5e38?, {0x1374a70?, 0xc00018a1c0?}, 0x100e045?)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:2084 +0x2f
net/http.(*ServeMux).ServeHTTP(0xc00010e310?, {0x1374a70, 0xc00018a1c0}, 0xc00019e200)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:2462 +0x149
net/http.serverHandler.ServeHTTP({0xc000113170?}, {0x1374a70, 0xc00018a1c0}, 0xc00019e200)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc000132b40, {0x1374cc8, 0xc000112ea0})
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:3071 +0x4db
2022/08/10 14:30:19 http: panic serving 127.0.0.1:51783: runtime error: index out of range [1] with length 0
goroutine 39 [running]:
net/http.(*conn).serve.func1()
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:1825 +0xbf
panic({0x12d8f40, 0xc0001501b0})
	/usr/local/Cellar/go/1.18.3/libexec/src/runtime/panic.go:844 +0x258
main.generateReportHandler({0x1374a70?, 0xc00018a2a0?}, 0xc00019e300)
	/Users/peter/duo-device-health/main.go:99 +0xdcb
net/http.HandlerFunc.ServeHTTP(0x25a5e38?, {0x1374a70?, 0xc00018a2a0?}, 0x100e045?)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:2084 +0x2f
net/http.(*ServeMux).ServeHTTP(0xc00010e510?, {0x1374a70, 0xc00018a2a0}, 0xc00019e300)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:2462 +0x149
net/http.serverHandler.ServeHTTP({0xc000113470?}, {0x1374a70, 0xc00018a2a0}, 0xc00019e300)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc000132d20, {0x1374cc8, 0xc000112ea0})
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:3071 +0x4db
2022/08/10 14:30:19 http: panic serving 127.0.0.1:51784: runtime error: index out of range [1] with length 0
goroutine 41 [running]:
net/http.(*conn).serve.func1()
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:1825 +0xbf
panic({0x12d8f40, 0xc000150228})
	/usr/local/Cellar/go/1.18.3/libexec/src/runtime/panic.go:844 +0x258
main.generateReportHandler({0x1374a70?, 0xc00018a380?}, 0xc00019e400)
	/Users/peter/duo-device-health/main.go:99 +0xdcb
net/http.HandlerFunc.ServeHTTP(0x25a5e38?, {0x1374a70?, 0xc00018a380?}, 0x100e045?)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:2084 +0x2f
net/http.(*ServeMux).ServeHTTP(0xc00010e710?, {0x1374a70, 0xc00018a380}, 0xc00019e400)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:2462 +0x149
net/http.serverHandler.ServeHTTP({0xc000113710?}, {0x1374a70, 0xc00018a380}, 0xc00019e400)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc000132f00, {0x1374cc8, 0xc000112ea0})
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:3071 +0x4db
2022/08/10 14:30:19 http: panic serving 127.0.0.1:51785: runtime error: index out of range [1] with length 0
goroutine 43 [running]:
net/http.(*conn).serve.func1()
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:1825 +0xbf
panic({0x12d8f40, 0xc0001502a0})
	/usr/local/Cellar/go/1.18.3/libexec/src/runtime/panic.go:844 +0x258
main.generateReportHandler({0x1374a70?, 0xc00018a460?}, 0xc00019e500)
	/Users/peter/duo-device-health/main.go:99 +0xdcb
net/http.HandlerFunc.ServeHTTP(0x25a5e38?, {0x1374a70?, 0xc00018a460?}, 0x100e045?)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:2084 +0x2f
net/http.(*ServeMux).ServeHTTP(0xc00010e910?, {0x1374a70, 0xc00018a460}, 0xc00019e500)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:2462 +0x149
net/http.serverHandler.ServeHTTP({0xc0001139b0?}, {0x1374a70, 0xc00018a460}, 0xc00019e500)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc0001330e0, {0x1374cc8, 0xc000112ea0})
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:3071 +0x4db
2022/08/10 14:30:19 http: panic serving 127.0.0.1:51794: runtime error: index out of range [1] with length 0
goroutine 45 [running]:
net/http.(*conn).serve.func1()
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:1825 +0xbf
panic({0x12d8f40, 0xc000150390})
	/usr/local/Cellar/go/1.18.3/libexec/src/runtime/panic.go:844 +0x258
main.generateReportHandler({0x1374a70?, 0xc00018a7e0?}, 0xc00019e800)
	/Users/peter/duo-device-health/main.go:99 +0xdcb
net/http.HandlerFunc.ServeHTTP(0x25a5e38?, {0x1374a70?, 0xc00018a7e0?}, 0x100e045?)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:2084 +0x2f
net/http.(*ServeMux).ServeHTTP(0xc00010eb10?, {0x1374a70, 0xc00018a7e0}, 0xc00019e800)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:2462 +0x149
net/http.serverHandler.ServeHTTP({0xc000113c50?}, {0x1374a70, 0xc00018a7e0}, 0xc00019e800)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc0001332c0, {0x1374cc8, 0xc000112ea0})
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:3071 +0x4db
2022/08/10 14:30:19 http: panic serving 127.0.0.1:51800: runtime error: index out of range [1] with length 0
goroutine 49 [running]:
net/http.(*conn).serve.func1()
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:1825 +0xbf
panic({0x12d8f40, 0xc000150408})
	/usr/local/Cellar/go/1.18.3/libexec/src/runtime/panic.go:844 +0x258
main.generateReportHandler({0x1374a70?, 0xc00018a8c0?}, 0xc00019e900)
	/Users/peter/duo-device-health/main.go:99 +0xdcb
net/http.HandlerFunc.ServeHTTP(0x25a5e38?, {0x1374a70?, 0xc00018a8c0?}, 0x100e045?)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:2084 +0x2f
net/http.(*ServeMux).ServeHTTP(0xc00010ed10?, {0x1374a70, 0xc00018a8c0}, 0xc00019e900)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:2462 +0x149
net/http.serverHandler.ServeHTTP({0xc000332030?}, {0x1374a70, 0xc00018a8c0}, 0xc00019e900)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc0001334a0, {0x1374cc8, 0xc000112ea0})
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:3071 +0x4db
2022/08/10 14:30:19 http: panic serving 127.0.0.1:51801: runtime error: index out of range [1] with length 0
goroutine 51 [running]:
net/http.(*conn).serve.func1()
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:1825 +0xbf
panic({0x12d8f40, 0xc000150480})
	/usr/local/Cellar/go/1.18.3/libexec/src/runtime/panic.go:844 +0x258
main.generateReportHandler({0x1374a70?, 0xc00018a9a0?}, 0xc00019ea00)
	/Users/peter/duo-device-health/main.go:99 +0xdcb
net/http.HandlerFunc.ServeHTTP(0x25a5e38?, {0x1374a70?, 0xc00018a9a0?}, 0x100e045?)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:2084 +0x2f
net/http.(*ServeMux).ServeHTTP(0xc00010ef10?, {0x1374a70, 0xc00018a9a0}, 0xc00019ea00)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:2462 +0x149
net/http.serverHandler.ServeHTTP({0xc0003322d0?}, {0x1374a70, 0xc00018a9a0}, 0xc00019ea00)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc000133680, {0x1374cc8, 0xc000112ea0})
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:3071 +0x4db
2022/08/10 14:30:19 http: panic serving 127.0.0.1:51802: runtime error: index out of range [1] with length 0
goroutine 53 [running]:
net/http.(*conn).serve.func1()
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:1825 +0xbf
panic({0x12d8f40, 0xc0001504f8})
	/usr/local/Cellar/go/1.18.3/libexec/src/runtime/panic.go:844 +0x258
main.generateReportHandler({0x1374a70?, 0xc00018aa80?}, 0xc00019eb00)
	/Users/peter/duo-device-health/main.go:99 +0xdcb
net/http.HandlerFunc.ServeHTTP(0x25a5e38?, {0x1374a70?, 0xc00018aa80?}, 0x100e045?)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:2084 +0x2f
net/http.(*ServeMux).ServeHTTP(0xc00010f110?, {0x1374a70, 0xc00018aa80}, 0xc00019eb00)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:2462 +0x149
net/http.serverHandler.ServeHTTP({0xc000332570?}, {0x1374a70, 0xc00018aa80}, 0xc00019eb00)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc000133860, {0x1374cc8, 0xc000112ea0})
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:3071 +0x4db
2022/08/10 14:30:19 http: panic serving 127.0.0.1:51803: runtime error: index out of range [1] with length 0
goroutine 55 [running]:
net/http.(*conn).serve.func1()
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:1825 +0xbf
panic({0x12d8f40, 0xc000150570})
	/usr/local/Cellar/go/1.18.3/libexec/src/runtime/panic.go:844 +0x258
main.generateReportHandler({0x1374a70?, 0xc00018ab60?}, 0xc00019ec00)
	/Users/peter/duo-device-health/main.go:99 +0xdcb
net/http.HandlerFunc.ServeHTTP(0x25a5e38?, {0x1374a70?, 0xc00018ab60?}, 0x100e045?)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:2084 +0x2f
net/http.(*ServeMux).ServeHTTP(0xc00010f310?, {0x1374a70, 0xc00018ab60}, 0xc00019ec00)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:2462 +0x149
net/http.serverHandler.ServeHTTP({0xc000332810?}, {0x1374a70, 0xc00018ab60}, 0xc00019ec00)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc000133a40, {0x1374cc8, 0xc000112ea0})
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:3071 +0x4db
2022/08/10 14:30:19 http: panic serving 127.0.0.1:51804: runtime error: index out of range [1] with length 0
goroutine 57 [running]:
net/http.(*conn).serve.func1()
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:1825 +0xbf
panic({0x12d8f40, 0xc0001505e8})
	/usr/local/Cellar/go/1.18.3/libexec/src/runtime/panic.go:844 +0x258
main.generateReportHandler({0x1374a70?, 0xc00018ac40?}, 0xc00019ed00)
	/Users/peter/duo-device-health/main.go:99 +0xdcb
net/http.HandlerFunc.ServeHTTP(0x25a5e38?, {0x1374a70?, 0xc00018ac40?}, 0x100e045?)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:2084 +0x2f
net/http.(*ServeMux).ServeHTTP(0xc00010f510?, {0x1374a70, 0xc00018ac40}, 0xc00019ed00)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:2462 +0x149
net/http.serverHandler.ServeHTTP({0xc000332ab0?}, {0x1374a70, 0xc00018ac40}, 0xc00019ed00)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc000133c20, {0x1374cc8, 0xc000112ea0})
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:3071 +0x4db
2022/08/10 14:30:19 http: panic serving 127.0.0.1:51805: runtime error: index out of range [1] with length 0
goroutine 59 [running]:
net/http.(*conn).serve.func1()
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:1825 +0xbf
panic({0x12d8f40, 0xc000150660})
	/usr/local/Cellar/go/1.18.3/libexec/src/runtime/panic.go:844 +0x258
main.generateReportHandler({0x1374a70?, 0xc00018ad20?}, 0xc00019ee00)
	/Users/peter/duo-device-health/main.go:99 +0xdcb
net/http.HandlerFunc.ServeHTTP(0x25a5e38?, {0x1374a70?, 0xc00018ad20?}, 0x100e045?)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:2084 +0x2f
net/http.(*ServeMux).ServeHTTP(0xc00010f710?, {0x1374a70, 0xc00018ad20}, 0xc00019ee00)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:2462 +0x149
net/http.serverHandler.ServeHTTP({0xc000332d50?}, {0x1374a70, 0xc00018ad20}, 0xc00019ee00)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc000133e00, {0x1374cc8, 0xc000112ea0})
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:3071 +0x4db
2022/08/10 14:30:19 http: panic serving 127.0.0.1:51806: runtime error: index out of range [1] with length 0
goroutine 61 [running]:
net/http.(*conn).serve.func1()
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:1825 +0xbf
panic({0x12d8f40, 0xc0001506d8})
	/usr/local/Cellar/go/1.18.3/libexec/src/runtime/panic.go:844 +0x258
main.generateReportHandler({0x1374a70?, 0xc00018ae00?}, 0xc00019ef00)
	/Users/peter/duo-device-health/main.go:99 +0xdcb
net/http.HandlerFunc.ServeHTTP(0x25a5e38?, {0x1374a70?, 0xc00018ae00?}, 0x100e045?)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:2084 +0x2f
net/http.(*ServeMux).ServeHTTP(0xc00010f910?, {0x1374a70, 0xc00018ae00}, 0xc00019ef00)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:2462 +0x149
net/http.serverHandler.ServeHTTP({0xc000332ff0?}, {0x1374a70, 0xc00018ae00}, 0xc00019ef00)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc0003b0000, {0x1374cc8, 0xc000112ea0})
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:3071 +0x4db
2022/08/10 14:30:19 http: panic serving 127.0.0.1:51807: runtime error: index out of range [1] with length 0
goroutine 63 [running]:
net/http.(*conn).serve.func1()
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:1825 +0xbf
panic({0x12d8f40, 0xc000150750})
	/usr/local/Cellar/go/1.18.3/libexec/src/runtime/panic.go:844 +0x258
main.generateReportHandler({0x1374a70?, 0xc00018aee0?}, 0xc00019f000)
	/Users/peter/duo-device-health/main.go:99 +0xdcb
net/http.HandlerFunc.ServeHTTP(0x25a5e38?, {0x1374a70?, 0xc00018aee0?}, 0x100e045?)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:2084 +0x2f
net/http.(*ServeMux).ServeHTTP(0xc00010fb10?, {0x1374a70, 0xc00018aee0}, 0xc00019f000)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:2462 +0x149
net/http.serverHandler.ServeHTTP({0xc000333290?}, {0x1374a70, 0xc00018aee0}, 0xc00019f000)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc0003b01e0, {0x1374cc8, 0xc000112ea0})
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:3071 +0x4db
2022/08/10 14:30:19 http: panic serving 127.0.0.1:51808: runtime error: index out of range [1] with length 0
goroutine 65 [running]:
net/http.(*conn).serve.func1()
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:1825 +0xbf
panic({0x12d8f40, 0xc0001507c8})
	/usr/local/Cellar/go/1.18.3/libexec/src/runtime/panic.go:844 +0x258
main.generateReportHandler({0x1374a70?, 0xc00018afc0?}, 0xc00019f100)
	/Users/peter/duo-device-health/main.go:99 +0xdcb
net/http.HandlerFunc.ServeHTTP(0x25a5e38?, {0x1374a70?, 0xc00018afc0?}, 0x100e045?)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:2084 +0x2f
net/http.(*ServeMux).ServeHTTP(0xc00010fd10?, {0x1374a70, 0xc00018afc0}, 0xc00019f100)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:2462 +0x149
net/http.serverHandler.ServeHTTP({0xc000333530?}, {0x1374a70, 0xc00018afc0}, 0xc00019f100)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc0003b03c0, {0x1374cc8, 0xc000112ea0})
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:3071 +0x4db
```

**Comment by kippjohnson** [comment]
I am getting the same error

**Comment by gmazzola** [comment]
Duo introduced version 2 of their Device Health API, which breaks this repository slightly. The following patch works for the time being:

```diff
$ git diff main.go
diff --git a/main.go b/main.go
index a20e696..47b6950 100644
--- a/main.go
+++ b/main.go
@@ -92,7 +92,7 @@ func generateReportHandler(w http.ResponseWriter, r *http.Request) {
        jsonData := new(bytes.Buffer)
        json.NewEncoder(jsonData).Encode(body)

-       re := regexp.MustCompile(`https://2.endpointhealth.duosecurity.com/v1/healthapp/device/health\?_req_trace_group=(.*)\?`)
+       re := regexp.MustCompile(`https://2.endpointhealth.duosecurity.com/v2/healthapp/device/health\?_req_trace_group=(.*)`)
        results := re.FindSubmatch([]byte(r.URL.Query().Get("eh_service_url")))

        url := "https://2.endpointhealth.duosecurity.com/v1/healthapp/device/health?_req_trace_group=" +
$
```

**Comment by dzflack** [comment]
Thanks @gmazzola I no longer have access to Duo at work; i'll apply this diff ^
